modLoader="javafml"
loaderVersion="[35,)"
license="MIT"

[[mods]]
    modId="i18nupdatemod"
    version="${file.jarVersion}"
    displayName="I18n update Mod"
    authors="TartaricAcid, baka-gourd, exzhawk"
    description="自动汉化更新模组"
